export const  ALL_PRODUCTS_REQUEST='ALL_PRODUCTS_REQUEST'
export const  ALL_PRODUCTS_SUCESS='ALL_PRODUCTS_SUCESS'
export const  ALL_PRODUCTS_FAIL='ALL_PRODUCTS_FAIL'


export const  PRODUCTS_DETAILS_REQUEST='PRODUCTS_DETAILS_REQUEST'
export const  PRODUCTS_DETAILS_SUCCESS='PRODUCTS_DETAILS_SUCCESS'
export const  PRODUCTS_DETAILS_FAIL='PRODUCTS_DETAILS_FAIL'

export const  CLEAR_ERRORS='CLEAR_ERRORS'




